apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAoiNX/VyoXPOqScGQr0IxkTGc5SvcGofVHRGvMkU3VI8np8E4lDHBj5N9By+2tWBYtK58+IQxzJ4YXrWE0jR+0udykxSSla+AD+kE8sFH8xLflh+1w7VzMrWA+5Bo08npm/eBorBQro/bZbMUI85kgZwRyKHwWOMI1hdGInPkrE1ephhDvvTBh4owNake7125db07tWUyFW6gwwm6AmbquGzXdi9UZFaw9rk9yotbfsKtoaPEWz4RXhxMGZCdCuQtTMfquTXNtBmw+F+GlV94pxhL7FxzHqd/pmrPNtZlMlcvLbyQ7tOTlC5TNPL6HFgCn8KtyshNP9o3xnay7C6T7i3qbkIgfK8GGWOjQjN+WJ5Xevc9nrNpiO4G9xXuD3efzg1D9daoOcAwf0cyPY1E8F0iHIsy6oE8LcPUReTqpJ0PvVuXizdVoeThdEEn3NHowNvIzRuWK0Jhu68h6wmVIr3gk4Jd8QnL6Vh1l+6Eutna2bJwV2wXRG31UeUIP/wvNpFw68byQCWnfs2tT7qOhIwTDUCmMI0qZ1todxLPP8hSvBuMiqG7XPRD7o/IDIsGEW9lf1Z6wCRvFf5MneFn1bjNvifUlBY+SlQJlrxeT+H9b9Mb6VXdqeKExU3E/ktctTxUyNAXrprZOf9BoWQY5xusbUuVpc/S4GEtuRd/2dqH6z+vk5GpnkwDOOy/KJh7NTtUbEJAsFLcCEZXCwUSP+6ewvSWdyI/zZxizyPgcLdeThoN/HV1ey/Ba2xWsrFfm5lMAvt5bFLAz/EjEFwXuGaJQorEeaOJGSu0cwNBQrvs1A51GOeFskJd1/Ce0R+/4hdKISd3MMUZozTmZtXkjRauyTwUxX5caqJbsyrOJdML7vrJsGlmjRGvEFsm3aL21gp3m0bQocZeA4r58NZR8fRo=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default

